# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Have all privliges'),
            preserve_default=False,
        ),
    ]
